kind: Deployment
apiVersion: apps/v1
metadata:
   name: scdevops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: scdevops
   template:
      metadata:
        labels:
          app: scdevops
      spec:
       containers:
        - name: scdevops
          image: sivachandrika/pipeline-demo 
          imagePullPolicy: Always
          ports:
          - containerPort: 80