kind: Service                             
apiVersion: v1
metadata:
  name: scdevops
  labels:
    app: scdevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 32200
  selector:
    app: scdevops                    
  type: LoadBalancer         